import { PostListItemType } from '@/types/post.types';

export const POST_LIST: PostListItemType[] = [
  {
    id: '1',
    title: 'Nuxt3에서 마크다운 파일을 읽어 페이지에 띄우기',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    subCategory: 'vue/nuxt',
    description: 'fs 모듈을 이용하여 Nuxt3 페이지에 마크다운을 나타냅니다.',
    thumbnail: '1',
    route: 1,
    date: '2022.03.15',
  },
  {
    id: '2',
    title: 'vercel + nuxt3 전역 환경변수 설정하기',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    subCategory: 'vue/nuxt',
    description: 'vercel과 nuxt3에서 전역 환경변수를 설정합니다.',
    thumbnail: '2',
    route: 2,
    date: '2022.03.17',
  },
  {
    id: '3',
    title: '자주쓰는 vue3 <script setup> 기본 문법 정리',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    subCategory: 'vue/nuxt',
    description:
      'vue3 <script setup>에서 자주 사용하는 기본 문법을 정리합니다.',
    thumbnail: '3',
    route: 3,
    date: '2022.03.19',
  },
  {
    id: '4',
    title: 'nuxt3으로 배포한 사이트를 구글 애널리틱스에 등록하기',
    category: 'SEO',
    categoryId: 'seo',
    description:
      'vue-gtag를 이용하여 nuxt3 프로젝트를 구글 애널리틱스에 등록합니다.',
    thumbnail: '4',
    route: 4,
    date: '2022.03.19',
  },
  {
    id: '5',
    title: '복잡도와 Big O 표기법',
    category: '자료구조/알고리즘',
    categoryId: 'data-structure-and-algorithm',
    description: '복잡도와 Big O 표기법에 대한 정리',
    thumbnail: '5',
    route: 5,
    date: '2022.03.27',
  },
  {
    id: '6',
    title:
      'vue3 setup script 에서 부모 컴포넌트에서 자식 컴포넌트 변수/함수 사용하기',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    subCategory: 'vue/nuxt',
    description:
      'vue3 setup script 에서 부모 컴포넌트에서 자식 컴포넌트 변수/함수를 사용할 수 있습니다.',
    thumbnail: '6',
    route: 6,
    date: '2022.04.15',
  },
  {
    id: '7',
    title: '백준 1712번 손익분기점',
    category: '코딩테스트',
    categoryId: 'coding-test',
    subCategory: '백준',
    description: '백준 1712번 손익분기점에 대한 문제 해설입니다.',
    thumbnail: '7',
    route: 7,
    date: '2022.04.17',
  },
  {
    id: '8',
    title: '버블 정렬 (Bubble Sort)',
    category: '자료구조/알고리즘',
    categoryId: 'data-structure-and-algorithm',
    description: '버블 정렬에 대한 정리',
    thumbnail: '8',
    route: 8,
    date: '2022.07.29',
  },
  {
    id: '9',
    title: 'Turborepo를 이용하여 모노레포 구성하기',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    description:
      'Turborepo를 이용하여 모노레포를 구성하고 여러 내부 패키지를 만드는 방법에 대한 정리',
    route: 9,
    date: '2024.10.31',
  },
  {
    id: '10',
    title: 'Next.js 에서 구글 로그인 구현하기 + 구글 유저 정보 가져오기',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    description:
      'Next.js 에서 구글 로그인 구현과 외부 API를 이용해서 구글 유저 정보 가져오는 방법에 대한 정리',
    route: 10,
    date: '2024.11.26',
  },
  {
    id: '11',
    title: '네이버 책 검색 API를 사용해보자',
    category: '오픈소스',
    categoryId: 'open-source',
    description: '네이버 책 검색 API를 사용하는 방법에 대한 정리',
    route: 11,
    date: '2024.11.29',
  },
  {
    id: '12',
    title: 'Vercel Serverless 에다가 express 애플리케이션 작성/배포하기',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    description:
      'Vercel Serverless 에 express 애플리케이션 작성/배포하는 방법 정리',
    route: 12,
    date: '2024.12.09',
  },
  {
    id: '13',
    title: "Next.js 의 'use client' 지시어",
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    description:
      "Next.js 의 'use client' 지시어에 대한 것과 알맞은 상황에 대한 정리",
    route: 13,
    date: '2024.12.10',
  },
  {
    id: '14',
    title: 'Vue.js의 반응성 기법 (reactive, ref, computed)',
    category: '라이브러리/프레임워크',
    categoryId: 'library-and-framework',
    description: 'Vue.js의 반응성 기법 (reactive, ref, computed)에 대한 정리',
    route: 14,
    date: '2025.09.27',
  },
  {
    id: '15',
    title: 'JavaScript Web Worker',
    category: '언어',
    categoryId: 'language',
    description:
      '별도의 스레드를 생성하여 작업을 처리하는 Web Worker에 대한 설명',
    route: 15,
    date: '2025.10.11',
  },
  {
    id: '16',
    title: 'C++ 포인터와 참조',
    category: '언어',
    categoryId: 'language',
    description: 'C++ 포인터와 참조에 대한 설명',
    route: 16,
    date: '2025.10.23',
  },
];
